
export const DEFAULT_IMAGE_PROMPT: string[] = [
    "Create a realistic, techno-optimistic future scene in vintage-style colors. Focus on a single large, futuristic structure with sharp, brutalist minimalist architecture and clean, geometric lines. Surround it with subtle natural elements like reflective terrain, sparse glowing vegetation, or bioluminescent features. Place one person in the distance, adding scale and a sense of quiet interaction with the environment. The lighting should be warm and soft, with pastel tones and slight desaturation, evoking a nostalgic yet forward-looking atmosphere. Incorporate subtle film grain and imperfections to enhance the vintage aesthetic",
    "Depict a distant view of a techno-optimistic cityscape in vintage-style colors. Include clusters of large, sharp-cornered minimalist buildings with brutalist architecture, glowing edges, and harmonious integration into the surrounding natural environment. Use soft pastel lighting to bathe the scene, blending reflections, glowing pathways, and atmospheric mist to add depth. The composition should balance the city’s scale with an expansive star-filled sky, complete with subtle celestial details like planets, moons, or nebulae. Maintain a vintage film-inspired aesthetic with muted colors and soft textures",
    "Illustrate a serene, open futuristic landscape with no visible architecture or only subtle signs of technology. Focus on natural elements such as rolling reflective dunes, calm water pools, or glowing bioluminescent forests. The lighting should emphasize soft pastel tones with warm highlights, creating a tranquil, vintage atmosphere. Add a vast, star-filled sky with distant planets or nebulae to evoke cosmic wonder. Keep the scene minimalistic but incorporate a sense of harmony and balance between natural beauty and subtle futuristic touches, cinematic haze, matte finish, soft diffusion, desaturated tones, atmospheric bloom, ethereal opacity, dreamy contrast, film grain, twilight shadows, misty ambiance.",
    "Design an abstract, futuristic composition in dark cold temperature monotone colors that inspires awe and wonder. Sharp, geometric forms and large brutalist architectural elements, blending glowing edges, reflective textures, and minimalist shapes in the distance. Include celestial motifs like stars, subtle planets, or abstract interpretations of orbiting structures. Use soft gradients, pastel tones, and muted colors to evoke a nostalgic yet futuristic feel. Let the scene feel surreal and open to interpretation, enhanced with vintage film grain and textures. cinematic haze, matte finish, soft diffusion, desaturated tones, atmospheric bloom, ethereal opacity, dreamy contrast, film grain, twilight shadows, misty ambiance, focus on large dark starry sky.Future earth society advanced achieved by advances in AGI",
    "Design an abstract, futuristic composition in vintage-style colors that inspires awe and wonder. Focus on sharp, geometric forms and large brutalist architectural elements, blending glowing edges, reflective textures, and minimalist shapes. Include celestial motifs like stars, subtle planets, or abstract interpretations of orbiting structures. Use soft gradients, pastel tones, and muted colors to evoke a nostalgic yet futuristic feel. Let the scene feel surreal and open to interpretation while maintaining a harmonious balance between structure and emptiness, enhanced with vintage film grain and textures",
];
export const DEFAULT_IMAGE_SIZE: string = "landscape_16_9";
export const DEFAULT_NUM_IMAGES: number = 1;
